'use strict';var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.inherits=function(a,d){function f(){}f.prototype=d.prototype;a.prototype=new f;a.prototype.constructor=a;for(var h in d)if(Object.defineProperties){var l=Object.getOwnPropertyDescriptor(d,h);l&&Object.defineProperty(a,h,l)}else a[h]=d[h]};
(function(a,d){"function"===typeof define&&define.amd?define(d):"object"===typeof exports?module.exports=d(require,exports,module):a.Tether=d()})(this,function(a,d,f){function h(g,a){if(!(g instanceof a))throw new TypeError("Cannot call a class as a function");}function l(a){var g=a.getBoundingClientRect(),b={},e;for(e in g)b[e]=g[e];a.ownerDocument!==document&&(a=a.ownerDocument.defaultView.frameElement)&&(a=l(a),b.top+=a.top,b.bottom+=a.top,b.left+=a.left,b.right+=a.left);return b}function r(a){var g=
(getComputedStyle(a)||{}).position,b=[];if("fixed"===g)return[a];for(var e=a;(e=e.parentNode)&&e&&1===e.nodeType;){var E=void 0;try{E=getComputedStyle(e)}catch(la){}if("undefined"===typeof E||null===E)return b.push(e),b;var d=E;/(auto|scroll)/.test(d.overflow+d.overflowY+d.overflowX)&&("absolute"!==g||0<=["relative","absolute","fixed"].indexOf(E.position))&&b.push(e)}b.push(a.ownerDocument.body);a.ownerDocument!==document&&b.push(a.ownerDocument.defaultView);return b}function q(){F&&document.body.removeChild(F);
F=null}function x(a){var g;a===document?(g=document,a=document.documentElement):g=a.ownerDocument;var b=g.documentElement;a=l(a);var e=ca();a.top-=e.top;a.left-=e.left;"undefined"===typeof a.width&&(a.width=document.body.scrollWidth-a.left-a.right);"undefined"===typeof a.height&&(a.height=document.body.scrollHeight-a.top-a.bottom);a.top-=b.clientTop;a.left-=b.clientLeft;a.right=g.body.clientWidth-a.width-a.left;a.bottom=g.body.clientHeight-a.height-a.top;return a}function G(a){return a.offsetParent||
document.documentElement}function K(){var a=document.createElement("div");a.style.width="100%";a.style.height="200px";var c=document.createElement("div");y(c.style,{position:"absolute",top:0,left:0,pointerEvents:"none",visibility:"hidden",width:"200px",height:"150px",overflow:"hidden"});c.appendChild(a);document.body.appendChild(c);var b=a.offsetWidth;c.style.overflow="scroll";a=a.offsetWidth;b===a&&(a=c.clientWidth);document.body.removeChild(c);c=b-a;return{width:c,height:c}}function y(){var a=0>=
arguments.length||void 0===arguments[0]?{}:arguments[0],c=[];Array.prototype.push.apply(c,arguments);c.slice(1).forEach(function(b){if(b)for(var e in b)({}).hasOwnProperty.call(b,e)&&(a[e]=b[e])});return a}function D(a,c){"undefined"!==typeof a.classList?c.split(" ").forEach(function(b){b.trim()&&a.classList.remove(b)}):(c=new RegExp("(^| )"+c.split(" ").join("|")+"( |$)","gi"),c=R(a).replace(c," "),a.setAttribute("class",c))}function C(a,c){"undefined"!==typeof a.classList?c.split(" ").forEach(function(b){b.trim()&&
a.classList.add(b)}):(D(a,c),c=R(a)+(" "+c),a.setAttribute("class",c))}function S(a,c){if("undefined"!==typeof a.classList)return a.classList.contains(c);a=R(a);return(new RegExp("(^| )"+c+"( |$)","gi")).test(a)}function R(a){return a.className instanceof a.ownerDocument.defaultView.SVGAnimatedString?a.className.baseVal:a.className}function z(a,c,b){b.forEach(function(b){-1===c.indexOf(b)&&S(a,b)&&D(a,b)});c.forEach(function(b){S(a,b)||C(a,b)})}function h(a,c){if(!(a instanceof c))throw new TypeError("Cannot call a class as a function");
}function da(a,c){if("function"!==typeof c&&null!==c)throw new TypeError("Super expression must either be null or a function, not "+typeof c);a.prototype=Object.create(c&&c.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});c&&(Object.setPrototypeOf?Object.setPrototypeOf(a,c):a.__proto__=c)}function ea(a,c){var b=2>=arguments.length||void 0===arguments[2]?1:arguments[2];return a+b>=c&&c>=a-b}function T(){return"undefined"!==typeof performance&&"undefined"!==typeof performance.now?
performance.now():+new Date}function W(){for(var a={top:0,left:0},c=arguments.length,b=Array(c),e=0;e<c;e++)b[e]=arguments[e];b.forEach(function(b){var e=b.top;b=b.left;"string"===typeof e&&(e=parseFloat(e,10));"string"===typeof b&&(b=parseFloat(b,10));a.top+=e;a.left+=b});return a}function L(a,c){"string"===typeof a.left&&-1!==a.left.indexOf("%")&&(a.left=parseFloat(a.left,10)/100*c.width);"string"===typeof a.top&&-1!==a.top.indexOf("%")&&(a.top=parseFloat(a.top,10)/100*c.height);return a}function fa(a,
c){"scrollParent"===c?c=a.scrollParents[0]:"window"===c&&(c=[pageXOffset,pageYOffset,innerWidth+pageXOffset,innerHeight+pageYOffset]);c===document&&(c=c.documentElement);"undefined"!==typeof c.nodeType&&function(){var a=c,e=x(c),g=getComputedStyle(c);c=[e.left,e.top,e.width+e.left,e.height+e.top];a.ownerDocument!==document&&(a=a.ownerDocument.defaultView,c[0]+=a.pageXOffset,c[1]+=a.pageYOffset,c[2]+=a.pageXOffset,c[3]+=a.pageYOffset);ga.forEach(function(a,b){a=a[0].toUpperCase()+a.substr(1);c[b]=
"Top"===a||"Left"===a?c[b]+parseFloat(g["border"+a+"Width"]):c[b]-parseFloat(g["border"+a+"Width"])})}();return c}var U=function(){function a(a,b){for(var e=0;e<b.length;e++){var c=b[e];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(c,b,e){b&&a(c.prototype,b);e&&a(c,e);return c}}(),w=void 0;"undefined"===typeof w&&(w={modules:[]});var F=null,X=function(){var a=0;return function(){return++a}}(),M={},ca=function(){var a=
F;a||(a=document.createElement("div"),a.setAttribute("data-tether-id",X()),y(a.style,{top:0,left:0,position:"absolute"}),document.body.appendChild(a),F=a);var c=a.getAttribute("data-tether-id");"undefined"===typeof M[c]&&(M[c]=l(a),A(function(){delete M[c]}));return M[c]},Y=[],A=function(a){Y.push(a)},N=function(){for(var a;a=Y.pop();)a()};d=function(){function a(){h(this,a)}U(a,[{key:"on",value:function(a,b,e){var c=3>=arguments.length||void 0===arguments[3]?!1:arguments[3];"undefined"===typeof this.bindings&&
(this.bindings={});"undefined"===typeof this.bindings[a]&&(this.bindings[a]=[]);this.bindings[a].push({handler:b,ctx:e,once:c})}},{key:"once",value:function(a,b,e){this.on(a,b,e,!0)}},{key:"off",value:function(a,b){if("undefined"!==typeof this.bindings&&"undefined"!==typeof this.bindings[a])if("undefined"===typeof b)delete this.bindings[a];else for(var e=0;e<this.bindings[a].length;)this.bindings[a][e].handler===b?this.bindings[a].splice(e,1):++e}},{key:"trigger",value:function(a){if("undefined"!==
typeof this.bindings&&this.bindings[a]){for(var b=0,e=arguments.length,c=Array(1<e?e-1:0),d=1;d<e;d++)c[d-1]=arguments[d];for(;b<this.bindings[a].length;){var g=this.bindings[a][b],e=g.handler,d=g.once,g=g.ctx;"undefined"===typeof g&&(g=this);e.apply(g,c);d?this.bindings[a].splice(b,1):++b}}}}]);return a}();w.Utils={getActualBoundingClientRect:l,getScrollParents:r,getBounds:x,getOffsetParent:G,extend:y,addClass:C,removeClass:D,hasClass:S,updateClasses:z,defer:A,flush:N,uniqueId:X,Evented:d,getScrollBarSize:K,
removeUtilElements:q};"use strict";var I=function(){return function(a,c){if(Array.isArray(a))return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();if(Symbol.iterator in Object(a)){var b=[],e=!0,d=!1,g=void 0;try{$jscomp.initSymbol();$jscomp.initSymbolIterator();for(var f=a[Symbol.iterator](),u;!(e=(u=f.next()).done)&&(b.push(u.value),!c||b.length!==c);e=!0);}catch(H){d=!0,g=H}finally{try{if(!e&&f["return"])f["return"]()}finally{if(d)throw g;}}return b}throw new TypeError("Invalid attempt to destructure non-iterable instance");
}}(),U=function(){function a(a,b){for(var e=0;e<b.length;e++){var c=b[e];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}return function(c,b,e){b&&a(c.prototype,b);e&&a(c,e);return c}}(),ha=function(a,c,b){var e=!0;for(;e;)if(null===a&&(a=Function.prototype),e=Object.getOwnPropertyDescriptor(a,c),void 0===e){a=Object.getPrototypeOf(a);if(null===a)break;e=!0}else{if("value"in e)return e.value;c=e.get;return void 0===c?void 0:c.call(b)}};
if("undefined"===typeof w)throw Error("You must include the utils.js file before tether.js");a=w.Utils;var r=a.getScrollParents,x=a.getBounds,G=a.getOffsetParent,y=a.extend,C=a.addClass,D=a.removeClass,z=a.updateClasses,A=a.defer,N=a.flush,K=a.getScrollBarSize,q=a.removeUtilElements,O=function(){if("undefined"===typeof document)return"";for(var a=document.createElement("div"),c=["transform","WebkitTransform","OTransform","MozTransform","msTransform"],b=0;b<c.length;++b){var e=c[b];if(void 0!==a.style[e])return e}}(),
J=[],Z=function(){J.forEach(function(a){a.position(!1)});N()};(function(){var a=null,c=null,b=null,e=function ba(){"undefined"!==typeof c&&16<c?(c=Math.min(c-16,250),b=setTimeout(ba,250)):"undefined"!==typeof a&&10>T()-a||(null!=b&&(clearTimeout(b),b=null),a=T(),Z(),c=T()-a)};"undefined"!==typeof window&&"undefined"!==typeof window.addEventListener&&["resize","scroll","touchmove"].forEach(function(a){window.addEventListener(a,e)})})();var ia={center:"center",left:"right",right:"left"},ja={middle:"middle",
top:"bottom",bottom:"top"},P={top:0,left:0,middle:"50%",center:"50%",bottom:"100%",right:"100%"},ka=function(a,c){var b=a.left;a=a.top;"auto"===b&&(b=ia[c.left]);"auto"===a&&(a=ja[c.top]);return{left:b,top:a}},aa=function(a){var c=a.left,b=a.top;"undefined"!==typeof P[a.left]&&(c=P[a.left]);"undefined"!==typeof P[a.top]&&(b=P[a.top]);return{left:c,top:b}},Q=function(a){a=a.split(" ");a=I(a,2);return{top:a[0],left:a[1]}};a=function(a){function c(a){var b=this;h(this,c);ha(Object.getPrototypeOf(c.prototype),
"constructor",this).call(this);this.position=this.position.bind(this);J.push(this);this.history=[];this.setOptions(a,!1);w.modules.forEach(function(a){"undefined"!==typeof a.initialize&&a.initialize.call(b)});this.position()}da(c,a);U(c,[{key:"getClass",value:function(){var a=0>=arguments.length||void 0===arguments[0]?"":arguments[0],e=this.options.classes;return"undefined"!==typeof e&&e[a]?this.options.classes[a]:this.options.classPrefix?this.options.classPrefix+"-"+a:a}},{key:"setOptions",value:function(a){var b=
this,c=1>=arguments.length||void 0===arguments[1]?!0:arguments[1],d=this.options=y({offset:"0 0",targetOffset:"0 0",targetAttachment:"auto auto",classPrefix:"tether"},a),f=d.target,g=d.targetModifier;this.element=d.element;this.target=f;this.targetModifier=g;"viewport"===this.target?(this.target=document.body,this.targetModifier="visible"):"scroll-handle"===this.target&&(this.target=document.body,this.targetModifier="scroll-handle");["element","target"].forEach(function(a){if("undefined"===typeof b[a])throw Error("Tether Error: Both element and target must be defined");
"undefined"!==typeof b[a].jquery?b[a]=b[a][0]:"string"===typeof b[a]&&(b[a]=document.querySelector(b[a]))});C(this.element,this.getClass("element"));!1!==this.options.addTargetClasses&&C(this.target,this.getClass("target"));if(!this.options.attachment)throw Error("Tether Error: You must provide an attachment");this.targetAttachment=Q(this.options.targetAttachment);this.attachment=Q(this.options.attachment);this.offset=Q(this.options.offset);this.targetOffset=Q(this.options.targetOffset);"undefined"!==
typeof this.scrollParents&&this.disable();this.scrollParents="scroll-handle"===this.targetModifier?[this.target]:r(this.target);!1!==this.options.enabled&&this.enable(c)}},{key:"getTargetBounds",value:function(){if("undefined"!==typeof this.targetModifier){if("visible"===this.targetModifier){if(this.target===document.body)return{top:pageYOffset,left:pageXOffset,height:innerHeight,width:innerWidth};var a=x(this.target),e={height:a.height,width:a.width,top:a.top,left:a.left};e.height=Math.min(e.height,
a.height-(pageYOffset-a.top));e.height=Math.min(e.height,a.height-(a.top+a.height-(pageYOffset+innerHeight)));e.height=Math.min(innerHeight,e.height);e.height-=2;e.width=Math.min(e.width,a.width-(pageXOffset-a.left));e.width=Math.min(e.width,a.width-(a.left+a.width-(pageXOffset+innerWidth)));e.width=Math.min(innerWidth,e.width);e.width-=2;e.top<pageYOffset&&(e.top=pageYOffset);e.left<pageXOffset&&(e.left=pageXOffset);return e}if("scroll-handle"===this.targetModifier){var c=this.target;c===document.body?
(c=document.documentElement,a={left:pageXOffset,top:pageYOffset,height:innerHeight,width:innerWidth}):a=x(c);var d=getComputedStyle(c),e=0;if(c.scrollWidth>c.clientWidth||0<=[d.overflow,d.overflowX].indexOf("scroll")||this.target!==document.body)e=15;var f=a.height-parseFloat(d.borderTopWidth)-parseFloat(d.borderBottomWidth)-e,e={width:15,height:f/c.scrollHeight*f*.975,left:a.left+a.width-parseFloat(d.borderLeftWidth)-15},g=0;408>f&&this.target===document.body&&(g=-1.1E-4*Math.pow(f,2)-.00727*f+22.58);
this.target!==document.body&&(e.height=Math.max(e.height,24));e.top=this.target.scrollTop/(c.scrollHeight-f)*(f-e.height-g)+a.top+parseFloat(d.borderTopWidth);this.target===document.body&&(e.height=Math.max(e.height,24));return e}}else return x(this.target)}},{key:"clearCache",value:function(){this._cache={}}},{key:"cache",value:function(a,e){"undefined"===typeof this._cache&&(this._cache={});"undefined"===typeof this._cache[a]&&(this._cache[a]=e.call(this));return this._cache[a]}},{key:"enable",
value:function(){var a=this,e=0>=arguments.length||void 0===arguments[0]?!0:arguments[0];!1!==this.options.addTargetClasses&&C(this.target,this.getClass("enabled"));C(this.element,this.getClass("enabled"));this.enabled=!0;this.scrollParents.forEach(function(b){b!==a.target.ownerDocument&&b.addEventListener("scroll",a.position)});e&&this.position()}},{key:"disable",value:function(){var a=this;D(this.target,this.getClass("enabled"));D(this.element,this.getClass("enabled"));this.enabled=!1;"undefined"!==
typeof this.scrollParents&&this.scrollParents.forEach(function(b){b.removeEventListener("scroll",a.position)})}},{key:"destroy",value:function(){var a=this;this.disable();J.forEach(function(b,c){b===a&&J.splice(c,1)});0===J.length&&q()}},{key:"updateAttachClasses",value:function(a,e){var b=this;a=a||this.attachment;e=e||this.targetAttachment;"undefined"!==typeof this._addAttachClasses&&this._addAttachClasses.length&&this._addAttachClasses.splice(0,this._addAttachClasses.length);"undefined"===typeof this._addAttachClasses&&
(this._addAttachClasses=[]);var c=this._addAttachClasses;a.top&&c.push(this.getClass("element-attached")+"-"+a.top);a.left&&c.push(this.getClass("element-attached")+"-"+a.left);e.top&&c.push(this.getClass("target-attached")+"-"+e.top);e.left&&c.push(this.getClass("target-attached")+"-"+e.left);var d=[];"left top bottom right middle center".split(" ").forEach(function(a){d.push(b.getClass("element-attached")+"-"+a);d.push(b.getClass("target-attached")+"-"+a)});A(function(){"undefined"!==typeof b._addAttachClasses&&
(z(b.element,b._addAttachClasses,d),!1!==b.options.addTargetClasses&&z(b.target,b._addAttachClasses,d),delete b._addAttachClasses)})}},{key:"position",value:function(){var a=this,c=0>=arguments.length||void 0===arguments[0]?!0:arguments[0];if(this.enabled){this.clearCache();var d=ka(this.targetAttachment,this.attachment);this.updateAttachClasses(this.attachment,d);var f=this.cache("element-bounds",function(){return x(a.element)}),g=f.width,u=f.height;0===g&&0===u&&"undefined"!==typeof this.lastSize?
(u=this.lastSize,g=u.width,u=u.height):this.lastSize={width:g,height:u};for(var h=this.cache("target-bounds",function(){return a.getTargetBounds()}),l=L(aa(this.attachment),{width:g,height:u}),p=L(aa(d),h),n=L(this.offset,{width:g,height:u}),k=L(this.targetOffset,h),l=W(l,n),p=W(p,k),B=h.left+p.left-l.left,m=h.top+p.top-l.top,V=0;V<w.modules.length;++V){var q=w.modules[V].position.call(this,{left:B,top:m,targetAttachment:d,targetPos:h,elementPos:f,offset:l,targetOffset:p,manualOffset:n,manualTargetOffset:k,
scrollbarSize:r,attachment:this.attachment});if(!1===q)return!1;"undefined"!==typeof q&&"object"===typeof q&&(m=q.top,B=q.left)}var t={page:{top:m,left:B},viewport:{top:m-pageYOffset,bottom:pageYOffset-m-u+innerHeight,left:B-pageXOffset,right:pageXOffset-B-g+innerWidth}},v=this.target.ownerDocument,d=v.defaultView,r=void 0;v.body.scrollWidth>d.innerWidth&&(r=this.cache("scrollbar-size",K),t.viewport.bottom-=r.height);v.body.scrollHeight>d.innerHeight&&(r=this.cache("scrollbar-size",K),t.viewport.right-=
r.width);if(-1===["","static"].indexOf(v.body.style.position)||-1===["","static"].indexOf(v.body.parentElement.style.position))t.page.bottom=v.body.scrollHeight-m-u,t.page.right=v.body.scrollWidth-B-g;"undefined"!==typeof this.options.optimizations&&!1!==this.options.optimizations.moveElement&&"undefined"===typeof this.targetModifier&&function(){var b=a.cache("target-offsetparent",function(){return G(a.target)}),c=a.cache("target-offsetparent-bounds",function(){return x(b)}),e=getComputedStyle(b),
d={};["Top","Left","Bottom","Right"].forEach(function(a){d[a.toLowerCase()]=parseFloat(e["border"+a+"Width"])});c.right=v.body.scrollWidth-c.left-c.width+d.right;c.bottom=v.body.scrollHeight-c.top-c.height+d.bottom;t.page.top>=c.top+d.top&&t.page.bottom>=c.bottom&&t.page.left>=c.left+d.left&&t.page.right>=c.right&&(t.offset={top:t.page.top-c.top+b.scrollTop-d.top,left:t.page.left-c.left+b.scrollLeft-d.left})}();this.move(t);this.history.unshift(t);3<this.history.length&&this.history.pop();c&&N();
return!0}}},{key:"move",value:function(a){var c=this;if("undefined"!==typeof this.element.parentNode){var b={},d;for(d in a){b[d]={};for(var f in a[d]){for(var g=!1,h=0;h<this.history.length;++h){var l=this.history[h];if("undefined"!==typeof l[d]&&!ea(l[d][f],a[d][f])){g=!0;break}}g||(b[d][f]=!0)}}var p={top:"",left:"",right:"",bottom:""},n=function(a,b){if(!1!==("undefined"!==typeof c.options.optimizations?c.options.optimizations.gpu:null)){var e;a.top?(p.top=0,e=b.top):(p.bottom=0,e=-b.bottom);
a.left?(p.left=0,a=b.left):(p.right=0,a=-b.right);p[O]="translateX("+Math.round(a)+"px) translateY("+Math.round(e)+"px)";"msTransform"!==O&&(p[O]+=" translateZ(0)")}else a.top?p.top=b.top+"px":p.bottom=b.bottom+"px",a.left?p.left=b.left+"px":p.right=b.right+"px"},k=!1;(b.page.top||b.page.bottom)&&(b.page.left||b.page.right)?(p.position="absolute",n(b.page,a.page)):(b.viewport.top||b.viewport.bottom)&&(b.viewport.left||b.viewport.right)?(p.position="fixed",n(b.viewport,a.viewport)):"undefined"!==typeof b.offset&&
b.offset.top&&b.offset.left?function(){p.position="absolute";var e=c.cache("target-offsetparent",function(){return G(c.target)});G(c.element)!==e&&A(function(){c.element.parentNode.removeChild(c.element);e.appendChild(c.element)});n(b.offset,a.offset);k=!0}():(p.position="absolute",n({top:!0,left:!0},a.page));if(!k){d=!0;for(g=this.element.parentNode;g&&1===g.nodeType&&"BODY"!==g.tagName;){if("static"!==getComputedStyle(g).position){d=!1;break}g=g.parentNode}d||(this.element.parentNode.removeChild(this.element),
this.element.ownerDocument.body.appendChild(this.element))}var B={};d=!1;for(f in p)g=p[f],this.element.style[f]!==g&&(d=!0,B[f]=g);d&&A(function(){y(c.element.style,B)})}}}]);return c}(d);a.modules=[];w.position=Z;d=y(a,w);"use strict";I=function(){return function(a,c){if(Array.isArray(a))return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();if(Symbol.iterator in Object(a)){var b=[],e=!0,d=!1,f=void 0;try{$jscomp.initSymbol();$jscomp.initSymbolIterator();for(var g=a[Symbol.iterator](),h;!(e=
(h=g.next()).done)&&(b.push(h.value),!c||b.length!==c);e=!0);}catch(H){d=!0,f=H}finally{try{if(!e&&g["return"])g["return"]()}finally{if(d)throw f;}}return b}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();a=w.Utils;var x=a.getBounds,y=a.extend,z=a.updateClasses,A=a.defer,ga=["left","top","right","bottom"];w.modules.push({position:function(a){var c=this,b=a.top,e=a.left,d=a.targetAttachment;if(!this.options.constraints)return!0;a=this.cache("element-bounds",function(){return x(c.element)});
var f=a.height,g=a.width;0===g&&0===f&&"undefined"!==typeof this.lastSize&&(a=this.lastSize,g=a.width,f=a.height);a=this.cache("target-bounds",function(){return c.getTargetBounds()});var h=a.height,l=a.width,q=[this.getClass("pinned"),this.getClass("out-of-bounds")];this.options.constraints.forEach(function(a){var b=a.outOfBoundsClass;a=a.pinnedClass;b&&q.push(b);a&&q.push(a)});q.forEach(function(a){["left","top","right","bottom"].forEach(function(b){q.push(a+"-"+b)})});var p=[],n=y({},d),k=y({},
this.attachment);this.options.constraints.forEach(function(a){var m=a.to,q=a.attachment;a=a.pin;"undefined"===typeof q&&(q="");var r=void 0,t=void 0;0<=q.indexOf(" ")?(t=q.split(" "),q=I(t,2),t=q[0],r=q[1]):r=t=q;m=fa(c,m);if("target"===t||"both"===t)b<m[1]&&"top"===n.top&&(b+=h,n.top="bottom"),b+f>m[3]&&"bottom"===n.top&&(b-=h,n.top="top");"together"===t&&("top"===n.top&&("bottom"===k.top&&b<m[1]?(b+=h,n.top="bottom",b+=f,k.top="top"):"top"===k.top&&b+f>m[3]&&b-(f-h)>=m[1]&&(b-=f-h,n.top="bottom",
k.top="bottom")),"bottom"===n.top&&("top"===k.top&&b+f>m[3]?(b-=h,n.top="top",b-=f,k.top="bottom"):"bottom"===k.top&&b<m[1]&&b+(2*f-h)<=m[3]&&(b+=f-h,n.top="top",k.top="top")),"middle"===n.top&&(b+f>m[3]&&"top"===k.top?(b-=f,k.top="bottom"):b<m[1]&&"bottom"===k.top&&(b+=f,k.top="top")));if("target"===r||"both"===r)e<m[0]&&"left"===n.left&&(e+=l,n.left="right"),e+g>m[2]&&"right"===n.left&&(e-=l,n.left="left");"together"===r&&(e<m[0]&&"left"===n.left?"right"===k.left?(e+=l,n.left="right",e+=g,k.left=
"left"):"left"===k.left&&(e+=l,n.left="right",e-=g,k.left="right"):e+g>m[2]&&"right"===n.left?"left"===k.left?(e-=l,n.left="left",e-=g,k.left="right"):"right"===k.left&&(e-=l,n.left="left",e+=g,k.left="left"):"center"===n.left&&(e+g>m[2]&&"left"===k.left?(e-=g,k.left="right"):e<m[0]&&"right"===k.left&&(e+=g,k.left="left")));if("element"===t||"both"===t)b<m[1]&&"bottom"===k.top&&(b+=f,k.top="top"),b+f>m[3]&&"top"===k.top&&(b-=f,k.top="bottom");if("element"===r||"both"===r)e<m[0]&&("right"===k.left?
(e+=g,k.left="left"):"center"===k.left&&(e+=g/2,k.left="left")),e+g>m[2]&&("left"===k.left?(e-=g,k.left="right"):"center"===k.left&&(e-=g/2,k.left="right"));"string"===typeof a?a=a.split(",").map(function(a){return a.trim()}):!0===a&&(a=["top","left","right","bottom"]);a=a||[];var v=[],u=[];b<m[1]&&(0<=a.indexOf("top")?(b=m[1],v.push("top")):u.push("top"));b+f>m[3]&&(0<=a.indexOf("bottom")?(b=m[3]-f,v.push("bottom")):u.push("bottom"));e<m[0]&&(0<=a.indexOf("left")?(e=m[0],v.push("left")):u.push("left"));
e+g>m[2]&&(0<=a.indexOf("right")?(e=m[2]-g,v.push("right")):u.push("right"));v.length&&function(){var a=void 0,a="undefined"!==typeof c.options.pinnedClass?c.options.pinnedClass:c.getClass("pinned");p.push(a);v.forEach(function(b){p.push(a+"-"+b)})}();u.length&&function(){var a=void 0,a="undefined"!==typeof c.options.outOfBoundsClass?c.options.outOfBoundsClass:c.getClass("out-of-bounds");p.push(a);u.forEach(function(b){p.push(a+"-"+b)})}();if(0<=v.indexOf("left")||0<=v.indexOf("right"))k.left=n.left=
!1;if(0<=v.indexOf("top")||0<=v.indexOf("bottom"))k.top=n.top=!1;if(n.top!==d.top||n.left!==d.left||k.top!==c.attachment.top||k.left!==c.attachment.left)c.updateAttachClasses(k,n),c.trigger("update",{attachment:k,targetAttachment:n})});A(function(){!1!==c.options.addTargetClasses&&z(c.target,p,q);z(c.element,p,q)});return{top:b,left:e}}});"use strict";a=w.Utils;x=a.getBounds;z=a.updateClasses;A=a.defer;w.modules.push({position:function(a){var c=this,b=a.top,e=a.left,d=this.cache("element-bounds",
function(){return x(c.element)});a=d.height;var d=d.width,f=this.getTargetBounds(),g=b+a,h=e+d,l=[];b<=f.bottom&&g>=f.top&&["left","right"].forEach(function(a){var b=f[a];b!==e&&b!==h||l.push(a)});e<=f.right&&h>=f.left&&["top","bottom"].forEach(function(a){var c=f[a];c!==b&&c!==g||l.push(a)});var q=[],p=[];q.push(this.getClass("abutted"));["left","top","right","bottom"].forEach(function(a){q.push(c.getClass("abutted")+"-"+a)});l.length&&p.push(this.getClass("abutted"));l.forEach(function(a){p.push(c.getClass("abutted")+
"-"+a)});A(function(){!1!==c.options.addTargetClasses&&z(c.target,p,q);z(c.element,p,q)});return!0}});"use strict";I=function(){return function(a,c){if(Array.isArray(a))return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();if(Symbol.iterator in Object(a)){var b=[],e=!0,d=!1,f=void 0;try{$jscomp.initSymbol();$jscomp.initSymbolIterator();for(var g=a[Symbol.iterator](),h;!(e=(h=g.next()).done)&&(b.push(h.value),!c||b.length!==c);e=!0);}catch(H){d=!0,f=H}finally{try{if(!e&&g["return"])g["return"]()}finally{if(d)throw f;
}}return b}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();w.modules.push({position:function(a){var c=a.top;a=a.left;if(this.options.shift){var b=this.options.shift;"function"===typeof this.options.shift&&(b=this.options.shift.call(this,{top:c,left:a}));var e;"string"===typeof b?(b=b.split(" "),b[1]=b[1]||b[0],b=I(b,2),e=b[0],b=b[1],e=parseFloat(e,10),b=parseFloat(b,10)):(e=b.top,b=b.left);return{top:c+e,left:a+b}}}});return d});
var $jscomp$destructuring$var0=Tether.Utils,Evented=$jscomp$destructuring$var0.Evented,addClass=$jscomp$destructuring$var0.addClass,extend=$jscomp$destructuring$var0.extend,hasClass=$jscomp$destructuring$var0.hasClass,removeClass=$jscomp$destructuring$var0.removeClass,uniqueId=$jscomp$destructuring$var0.uniqueId,Shepherd=new Evented;function getVaadinOverlayContainer(){return document.getElementsByClassName("v-app v-overlay-container")[0]}
function getVaadinRootAppContainer(){return document.getElementsByClassName("v-app")[0]}function isUndefined(a){return"undefined"===typeof a}function isArray(a){return"[object Array]"===Object.prototype.toString.call(a)}function isObject(a){return"[object Object]"===Object.prototype.toString.call(a)}function isObjectLoose(a){return"object"===typeof a}
var ATTACHMENT={"top right":"bottom left","top left":"bottom right","top center":"bottom center","middle right":"middle left","middle left":"middle right","middle center":"middle center","bottom left":"top right","bottom right":"top left","bottom center":"top center",top:"bottom center",left:"middle right",right:"middle left",bottom:"top center",center:"middle center",middle:"middle center"};function createFromHTML(a){var d=document.createElement("div");d.innerHTML=a;return d.children[0]}
function matchesSelector(a,d){var f;isUndefined(a.matches)?isUndefined(a.matchesSelector)?isUndefined(a.msMatchesSelector)?isUndefined(a.webkitMatchesSelector)?isUndefined(a.mozMatchesSelector)?isUndefined(a.oMatchesSelector)||(f=a.oMatchesSelector):f=a.mozMatchesSelector:f=a.webkitMatchesSelector:f=a.msMatchesSelector:f=a.matchesSelector:f=a.matches;return f.call(a,d)}var positionRe=/^(.+) (top|left|right|bottom|center|\[[a-z ]+\])$/;
function parsePosition(a){if(isObjectLoose(a))return a.hasOwnProperty("element")&&a.hasOwnProperty("on")?a:null;a=positionRe.exec(a);if(!a)return null;var d=a[2];"["===d[0]&&(d=d.substring(1,d.length-1));return{element:a[1],on:d}}function parseShorthand(a,d){if(null===a||isUndefined(a)||isObjectLoose(a))return a;a=a.split(" ");for(var f={},h=d.length-1,l=a.length-1;0<=l;l--){if(0===h){f[d[h]]=a.slice(0,l+1).join(" ");break}else f[d[h]]=a[l];h--}return f}
var Step=function(a,d){Evented.call(this,a,d);this.tour=a;this.bindMethods();this.setOptions(d);return this};$jscomp.inherits(Step,Evented);Step.prototype.bindMethods=function(){var a=this;"_show show hide isOpen cancel complete scrollTo destroy render".split(" ").map(function(d){a[d]=a[d].bind(a)})};
Step.prototype.setOptions=function(a){this.options=a=void 0===a?{}:a;this.destroy();this.id=this.options.id||this.id||"step-"+uniqueId();if(a=this.options.when)for(var d in a)if({}.hasOwnProperty.call(a,d))this.on(d,a[d],this);a=JSON.stringify(this.options.buttons);d=isUndefined(a)||"true"===a;a="{}"===a||"[]"===a||"null"===a||"false"===a;var f=!d&&isArray(this.options.buttons),h=!d&&isObject(this.options.buttons);if(d)this.options.buttons=[{text:"Next",action:this.tour.next,classes:"btn"}];else if(!a&&
h)this.options.buttons=[this.options.buttons];else if(a||!f)this.options.buttons=!1};Step.prototype.getTour=function(){return this.tour};
Step.prototype.bindAdvance=function(){var a=this,d=parseShorthand(this.options.advanceOn,["selector","event"]),f=d.event,h=d.selector,l=function(d){a.isOpen()&&(isUndefined(h)?a.el&&d.target===a.el&&a.tour.next():matchesSelector(d.target,h)&&a.tour.next())};getVaadinOverlayContainer().addEventListener(f,l);this.on("destroy",function(){return getVaadinOverlayContainer().removeEventListener(f,l)})};
Step.prototype.getAttachTo=function(){var a=parsePosition(this.options.attachTo)||{},d=extend({},a);"string"===typeof a.element&&(d.element=document.querySelector(a.element),d.element||console.error("The element for this Shepherd step was not found "+a.element));return d};
Step.prototype.setupTether=function(){if(isUndefined(Tether))throw Error("Using the attachment feature of Shepherd requires the Tether library");var a=this.getAttachTo(),d=ATTACHMENT[a.on]||ATTACHMENT.right;isUndefined(a.element)&&(a.element="viewport",d="middle center");a={classPrefix:"shepherd",element:this.el,constraints:[{to:"window",pin:!0,attachment:"together"}],target:a.element,offset:a.offset||"0 0",attachment:d};this.tether&&this.tether.destroy();this.tether=new Tether(extend(a,this.options.tetherOptions))};
Step.prototype.show=function(a){a=void 0===a?!0:a;var d=this;if(!isUndefined(this.options.beforeShowPromise)){var f=this.options.beforeShowPromise();if(!isUndefined(f))return f.then(function(){return d._show(a)})}this._show(a)};
Step.prototype._show=function(a){var d=this;a&&this.trigger("before-show");this.el||this.render();addClass(this.el,"shepherd-open");this.options.modal&&addClass(getVaadinRootAppContainer(),"shepherd-modal");getVaadinOverlayContainer().setAttribute("data-shepherd-step",this.id);this.setupTether();this.options.scrollTo&&setTimeout(function(){d.scrollTo()});a&&this.trigger("show")};
Step.prototype.hide=function(){this.trigger("before-hide");removeClass(this.el,"shepherd-open");removeClass(getVaadinRootAppContainer(),"shepherd-modal");getVaadinOverlayContainer().removeAttribute("data-shepherd-step");this.tether&&this.tether.destroy();this.tether=null;this.trigger("hide")};Step.prototype.isOpen=function(){return this.el&&hasClass(this.el,"shepherd-open")};Step.prototype.cancel=function(){this.tour.cancel();this.trigger("cancel")};
Step.prototype.complete=function(){this.tour.complete();this.trigger("complete")};Step.prototype.scrollTo=function(){var a=this.getAttachTo().element;isUndefined(this.options.scrollToHandler)?isUndefined(a)||a.scrollIntoView():this.options.scrollToHandler(a)};
Step.prototype.destroy=function(a){a=void 0===a?!0:a;this.isOpen()&&removeClass(document.body,"shepherd-modal");!isUndefined(this.el)&&this.el.parentNode&&(this.el.parentNode.removeChild(this.el),delete this.el);this.tether&&this.tether.destroy();this.tether=null;a&&this.trigger("destroy")};
Step.prototype.render=function(){var a=this;isUndefined(this.el)||this.destroy();this.el=createFromHTML("\x3cdiv class\x3d'shepherd-step "+(this.options.classes||"")+"' data-id\x3d'"+this.id+"' "+(this.options.idAttribute?'id\x3d"'+this.options.idAttribute+'"':"")+"\x3e\x3c/div\x3e");var d=document.createElement("div");d.className="shepherd-content";null!=this.options.width&&(d.style.width=this.options.width);null!=this.options.height&&(d.style.height=this.options.height);this.el.appendChild(d);var f=
document.createElement("header");d.appendChild(f);this.options.title&&(f.innerHTML+="\x3cspan class\x3d'shepherd-title'\x3e"+this.options.title+"\x3c/span\x3e",this.el.className+=" shepherd-has-title");if(this.options.showCancelLink){var h=createFromHTML("\x3ca href class\x3d'shepherd-cancel-link'\x3e✕\x3c/a\x3e");f.appendChild(h);this.el.className+=" shepherd-has-cancel-link";this.bindCancelLink(h)}if(!isUndefined(this.options.text)){var l=createFromHTML("\x3cdiv class\x3d'shepherd-text'\x3e\x3c/div\x3e"),
f=this.options.text;"function"===typeof f&&(f=f.call(this,l));f instanceof HTMLElement?l.appendChild(f):("string"===typeof f&&(f=[f]),f.map(function(a){l.innerHTML+="\x3cp\x3e"+a+"\x3c/p\x3e"}));d.appendChild(l)}if(this.options.buttons){var f=document.createElement("footer"),r=createFromHTML("\x3cul class\x3d'shepherd-buttons'\x3e\x3c/ul\x3e");this.options.buttons.map(function(d){var f=createFromHTML("\x3cli\x3e\x3ca class\x3d'shepherd-button "+(d.classes||"")+" "+(d.buttonEnabled?"":"disabled")+
"'\x3e"+d.text+"\x3c/a\x3e");r.appendChild(f);d.buttonEnabled&&a.bindButtonEvents(d,f.querySelector("a"))});f.appendChild(r);d.appendChild(f)}getVaadinOverlayContainer().appendChild(this.el);this.setupTether();this.options.advanceOn&&this.bindAdvance()};Step.prototype.bindCancelLink=function(a){var d=this;a.addEventListener("click",function(a){a.preventDefault();d.cancel()})};
Step.prototype.bindButtonEvents=function(a,d){var f=this;a.events=a.events||{};isUndefined(a.action)||(a.events.click=a.action);var h={},l;for(l in a.events){if({}.hasOwnProperty.call(a.events,l)){var r=a.events[l];"string"===typeof r&&(h.page=r,r=function(a){return function(){return f.tour.show(a.page)}}(h));d.addEventListener(l,r)}h={page:h.page}}this.on("destroy",function(){for(var f in a.events)({}).hasOwnProperty.call(a.events,f)&&d.removeEventListener(f,a.events[f])})};
var Tour=function(a){a=void 0===a?{}:a;var d=this;Evented.call(this,a);this.bindMethods();this.options=a;this.steps=this.options.steps||[];"complete cancel hide start show active inactive".split(" ").map(function(a){(function(a){d.on(a,function(f){f=f||{};f.tour=d;Shepherd.trigger(a,f)})})(a)});return this};$jscomp.inherits(Tour,Evented);Tour.prototype.bindMethods=function(){var a=this;["next","back","cancel","complete","hide"].map(function(d){a[d]=a[d].bind(a)})};
Tour.prototype.addStep=function(a,d){isUndefined(d)&&(d=a);if(d instanceof Step)d.tour=this;else{if("string"===typeof a||"number"===typeof a)d.id=a.toString();d=extend({},this.options.defaults,d);d=new Step(this,d)}this.steps.push(d);return this};
Tour.prototype.removeStep=function(a){for(var d=this.getCurrentStep(),f=0;f<this.steps.length;++f){var h=this.steps[f];if(h.id===a){h.isOpen()&&h.hide();h.destroy();this.steps.splice(f,1);break}}d&&d.id===a&&(this.currentStep=void 0,this.steps.length?this.show(0):this.hide())};Tour.prototype.getById=function(a){for(var d=0;d<this.steps.length;++d){var f=this.steps[d];if(f.id===a)return f}};Tour.prototype.getCurrentStep=function(){return this.currentStep};
Tour.prototype.next=function(){var a=this.steps.indexOf(this.currentStep);a===this.steps.length-1?(this.hide(a),this.trigger("complete"),this.done()):this.show(a+1,!0)};Tour.prototype.back=function(){var a=this.steps.indexOf(this.currentStep);this.show(a-1,!1)};Tour.prototype.cancel=function(){this.currentStep&&this.currentStep.hide();this.trigger("cancel");this.done()};Tour.prototype.complete=function(){this.currentStep&&this.currentStep.hide();this.trigger("complete");this.done()};
Tour.prototype.hide=function(){this.currentStep&&this.currentStep.hide();this.trigger("hide");this.done()};Tour.prototype.done=function(){Shepherd.activeTour=null;removeClass(getVaadinRootAppContainer(),"shepherd-active");this.trigger("inactive",{tour:this})};
Tour.prototype.show=function(a,d,f){a=void 0===a?0:a;d=void 0===d?!0:d;f=void 0===f?!0:f;this.currentStep&&this.currentStep.isOpen()?this.currentStep.hide():(addClass(getVaadinRootAppContainer(),"shepherd-active"),this.trigger("active",{tour:this}));Shepherd.activeTour=this;if(a="string"===typeof a?this.getById(a):this.steps[a])isUndefined(a.options.showOn)||a.options.showOn()?(f&&this.trigger("show",{step:a,previous:this.currentStep}),this.currentStep&&this.currentStep.isOpen()&&this.currentStep.hide(),
this.currentStep=a,a.show(f)):(a=this.steps.indexOf(a),this.show(d?a+1:a-1,d,f))};Tour.prototype.start=function(){this.trigger("start");this.currentStep=null;this.next()};extend(Shepherd,{Tour:Tour,Step:Step,Evented:Evented});